# Variables
@baseUrl=http://localhost:3000

### Get all posts
GET {{ baseUrl }}/api/post?limit=10&skip=0

### Get post by id
GET {{ baseUrl }}/api/post/cm2fd23ed0000dpvoynfaco3x

### Create post
POST {{ baseUrl }}/api/post
Content-Type: application/json

{
    "title": "Post title",
    "content": "Post content"
}

### Update post
PATCH {{ baseUrl }}/api/post/cm2fd23ed0000dpvoynfaco3x
Content-Type: application/json

{
    "title": "Updated post title",
    "content": "Updated post content"
}

### Delete post
DELETE {{ baseUrl }}/api/post/cm2fd23ed0000dpvoynfaco3x
